// import img from '../../assets/images/icons/Avatar.png'
// let data= localStorage.choose_skin

export const getSvg =[
    {
      
      home:'assets/images/icons/Group 34696.png',
      home1:'assets/images/icons/home-2.png',
      home3:'assets/images/icons/home3.png',
      user:'assets/images/icons/Avatar.png',
      user1:'assets/images/icons/frame1.png',
      user3:'assets/images/icons/frame3.png',
      helpdesk:'assets/images/icons/profile-2user.png',
      helpdesk1:'assets/images/icons/helpdesk1.png',
      helpdesk3:'assets/images/icons/helpdesk3.png',
      project:'assets/images/icons/note.png',
      project1:'assets/images/icons/note1.png',
      project3:'assets/images/icons/note3.png',
      notification:'assets/images/icons/notification.png',
      notification1:'assets/images/icons/notification1.png',
      notification3:'assets/images/icons/notification3.png',
      Efms:'assets/images/icons/note.png',
      Efms1:'assets/images/icons/note1.png',
      Efms3:'assets/images/icons/note3.png',
      organization:'assets/images/icons/people.png' ,
      organization1:'assets/images/icons/people1.png' ,
      organization3:'assets/images/icons/people3.png' ,
      emossy:'assets/images/icons/calendar.png',
      emossy1:'assets/images/icons/calendar1.png',
      emossy3:'assets/images/icons/calendar3.png',
      ourEmployee:'assets/images/icons/personalcard.png',
      ourEmployee1:'assets/images/icons/personalcard1.png',
      ourEmployee3:'assets/images/icons/personalcard3.png',
      approval:'assets/images/icons/tick-circle.png',
      approval1:'assets/images/icons/tick-circle1.png',
      approval3:'assets/images/icons/tick-circle3.png',
      recruitment:'assets/images/icons/Group 34697.png',
      recruitment1:'assets/images/icons/Group 34697 1.png',
      recruitment3:'assets/images/icons/clint-master3.png',
      assetmaster:'assets/images/icons/3d-cube-scan.png',
      assetmaster1:'assets/images/icons/3d-cube-scan1.png',
      assetmaster3:'assets/images/icons/3d-cube-scan3.png',
      payroll:'assets/images/icons/card.png',
      payroll1:'assets/images/icons/card1.png',
      payroll3:'assets/images/icons/card3.png',
      career:'assets/images/icons/briefcase.png',
      career1:'assets/images/icons/briefcase1.png',
      career3:'assets/images/icons/briefcase3.png',
      performance:'assets/images/icons/status-up.png',
      performance1:'assets/images/icons/status-up1.png',
      performance3:'assets/images/icons/status-up3.png',
      ouritranet:'assets/images/icons/global-edit.png',
      ouritranet1:'assets/images/icons/global-edit1.png',
      ouritranet3:'assets/images/icons/global-edit3.png',
      faq:'assets/images/icons/message-question.png',
      faq1:'assets/images/icons/message-question1.png',
      faq3:'assets/images/icons/message-question3.png',
      permission:'assets/images/icons/verify.png',
      permission1:'assets/images/icons/verify1.png',
      permission3:'assets/images/icons/verify3.png',
      clientmaster:'assets/images/icons/user-square.png',
      clientmaster1:'assets/images/icons/user-square1.png',
      clientmaster3:'assets/images/icons/clint-master3.png',
      ProjectMaster: 'assets/images/document-text.svg',
      ProjectMaster1: 'assets/images/document-text-1.svg',
      ProjectsBoard: 'assets/images/Frame 1261155164.svg',
      ProjectsBoard1: 'assets/images/Frame 1261155164-1.svg',
      TaskApproval: 'assets/images/note.svg',
      TaskApproval1: 'assets/images/note-1.svg',
      ProjectReports: 'assets/images/tick-circle.svg',
      ProjectReports1: 'assets/images/tick-circle-1.svg'
    }
] 

// return this.Images;

