export interface emptyRow{
    taskId: "",  
    isChecked: false,
    disableInput: false, 
    projectName: null,
    projectId: null,
    taskName: "",
    isBillabel: false,
    totalWorkingTimeInProject: "00:00",
    allWorkingTimeInProject: 0.0,
    projectManagerId: null,
    taskRequestId: null, 
    taskRequestName: "Not_Selected",
    estimateTime: "00:00",
    startDate: "",
    endDate: "",
    re_EvaluteComment: null,
    isReEvaluet: false,
    isApproved: false,
    isSFA: false,
    estimateTimeLong: 480,
    description: "",
}