import { getSvg } from "src/app/svg/svgIcon";
import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/admin/dashboard/main",
    title: "Home",
    icon: getSvg[0]?.home,
    iconhoverblue: getSvg[0]?.home1,
    iconhoversaffron: getSvg[0]?.home3,
    isHover: false,
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "/employee-master/employee-onboarding",
    title: "Our Employee",
    icon: getSvg[0]?.helpdesk,
    iconhoverblue: getSvg[0]?.helpdesk1,
    iconhoversaffron: getSvg[0]?.helpdesk3,
    isHover: false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "employee-master/employee-onboarding",
        title: "Employee Onbording",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "employee-master/all-employee",
        title: "All Employee",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "employee-master/employee-directory",
        title: "Employee Directory",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
    ],
  },
  {
    path: "/assets-master/employee-onboarding",
    title: "Assets Master",
    icon: getSvg[0]?.helpdesk,
    iconhoverblue: getSvg[0]?.helpdesk1,
    iconhoversaffron: getSvg[0]?.helpdesk3,
    isHover: false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "assets-master/assets-dashboard",
        title: "Assets Dashboard",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "assets-master/expire-dashboard",
        title: "Expire Dashboard",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "assets-master/company-assets",
        title: "Company Assets",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "assets-master/assets-report",
        title: "Assets Report",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "assets-master/assets-warehouse-categories",
        title: "Warehouse",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "assets-master/assets-delete-archive",
        title: "Deleted Assets",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
    ],
  },
  {
    path: "/organization-master/organization",
    title: "Organization",
    icon: getSvg[0]?.helpdesk,
    iconhoverblue: getSvg[0]?.helpdesk1,
    iconhoversaffron: getSvg[0]?.helpdesk3,
    isHover: false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "/organization-master/organization",
        title: "Organization",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "/organization-master/department",
        title: "Department",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "/organization-master/designation",
        title: "Designation",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
    ],
  },
  {
    path: "/help-desk/ticket-dashboard",
    title: "Help Desk",
    icon: getSvg[0]?.helpdesk,
    iconhoverblue: getSvg[0]?.helpdesk1,
    iconhoversaffron: getSvg[0]?.helpdesk3,
    isHover: false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "help-desk/ticket-dashboard",
        title: "TICKET DASHBOARD",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "help-desk/ticket-category",
        title: "TICKET CATEGORY",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "help-desk/ticket-raised",
        title: "TICKET RAISED",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "help-desk/ticket-received",
        title: "TICKET RECEIVED",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "help-desk/ticket-report",
        title: "TICKET REPORT",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
    ],
  },
  {
    path: "/organization-master/organization",
    title: "Organization",
    icon: getSvg[0]?.helpdesk,
    iconhoverblue: getSvg[0]?.helpdesk1,
    iconhoversaffron: getSvg[0]?.helpdesk3,
    isHover: false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "/organization-master/organization",
        title: "Organization",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "/organization-master/department",
        title: "Department",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "/organization-master/designation",
        title: "Designation",
        icon: getSvg[0]?.user,
        iconhoverblue: getSvg[0]?.user1,
        iconhoversaffron: getSvg[0]?.home1,
        isHover: false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
    ],
  },
];
